/* ShelfLife — agent.js
   Real-store hand-off: turns the optimized cart (or the raw list) into a
   precise, guard-railed brief that an AI browsing agent — Claude with the
   Chrome extension, or any computer-use agent — can execute against a real
   grocer's website. No grocer exposes a public add-to-cart API, so the
   honest bridge from "simulated comparison" to "real cart" is an agent
   working the retailer's own site inside the user's signed-in session.
   Pure logic, no DOM — also exercised by dev/validate.js. */
(function (g) {
  'use strict';

  const RETAILERS = [
    { id: 'walmart',   name: 'Walmart',      url: 'https://www.walmart.com',  search: 'https://www.walmart.com/search?q={query}' },
    { id: 'kroger',    name: 'Kroger',       url: 'https://www.kroger.com',   search: 'https://www.kroger.com/search?query={query}' },
    { id: 'target',    name: 'Target',       url: 'https://www.target.com',   search: 'https://www.target.com/s?searchTerm={query}' },
    { id: 'safeway',   name: 'Safeway',      url: 'https://www.safeway.com',  search: 'https://www.safeway.com/shop/search-results.html?q={query}' },
    { id: 'heb',       name: 'H-E-B',        url: 'https://www.heb.com',      search: 'https://www.heb.com/search/?q={query}' },
    { id: 'instacart', name: 'Instacart',    url: 'https://www.instacart.com', search: 'https://www.instacart.com/store/s?k={query}' },
    { id: 'amazon',    name: 'Amazon Fresh', url: 'https://www.amazon.com/alm/storefront', search: 'https://www.amazon.com/s?k={query}&i=amazonfresh' }
  ];

  /* Build brief line items from the current cart (preferred: it already
     reflects packages and chosen substitutions) or from the checked list. */
  function itemsFromCart(cart, FOODS) {
    return cart.quotes.map((q) => {
      const food = FOODS.byId(q.boughtAs);
      return {
        foodId: food.id,
        name: food.name,
        qty: q.packages,
        pkg: food.pkg.label,
        subs: (food.subs || []).map((id) => FOODS.byId(id).name)
      };
    });
  }

  function itemsFromList(lines, FOODS) {
    return lines.map((l) => {
      const food = FOODS.byId(l.foodId);
      return {
        foodId: food.id,
        name: food.name,
        qty: l.packages,
        pkg: food.pkg.label,
        subs: (food.subs || []).map((id) => FOODS.byId(id).name)
      };
    });
  }

  /* The brief itself. Deliberately explicit about what the agent may and
     may not do: add to cart yes, checkout / payment / account changes no. */
  function buildBrief({ retailerId, mode, zip, items, budget }) {
    const r = RETAILERS.find((x) => x.id === retailerId) || RETAILERS[0];
    const fulfill = mode === 'delivery' ? 'delivery' : 'pickup';
    const where = zip ? (fulfill === 'delivery' ? 'delivery to ZIP ' + zip : 'pickup near ZIP ' + zip) : fulfill;

    const lines = items.map((it) => {
      let s = '- ' + it.qty + ' × ' + it.pkg + ' — ' + it.name;
      if (it.subs && it.subs.length) s += '  (ok to substitute: ' + it.subs.join(', ') + ')';
      return s;
    });

    return [
      '# Grocery cart brief — for an AI browsing agent',
      '',
      'Generated by ShelfLife. Execute this in the user’s own browser session.',
      '',
      '## Goal',
      'Fill an online cart at **' + r.name + '** (' + r.url + ') for ' + where + '.',
      'Add the items below to the cart, then STOP at cart review. Do not place the order.',
      '',
      '## Ground rules (non-negotiable)',
      '1. Use the user’s existing signed-in session. If the site is not signed in, pause and ask the user to sign in themselves — never enter credentials.',
      '2. Never enter payment, address, or password details. Never click Place order / Checkout / Buy now.',
      '3. Set the fulfillment method to ' + fulfill + (zip ? ' for ZIP ' + zip : '') + ' before adding items, so prices and availability are correct.',
      '4. For each item, pick the option closest to the listed package size; the store brand is fine when it’s cheaper. Small size differences are acceptable.',
      '5. If an item is out of stock, use one of its listed substitutes. If none are available, skip it and note it — don’t improvise unlisted replacements.',
      '6. When every item is handled, stop at the cart page and report: items added, items substituted, items skipped, and the cart total' + (budget ? ' compared to the ~' + '$' + budget.toFixed(2) + ' estimate' : '') + '.',
      '',
      '## Items (' + items.length + ')',
      ...lines,
      '',
      '## Handy search URL',
      'Item search template: ' + r.search.replace('{query}', '<item name>'),
      ''
    ].join('\n');
  }

  g.SL = g.SL || {};
  g.SL.agent = { RETAILERS, buildBrief, itemsFromCart, itemsFromList };
})(typeof window !== 'undefined' ? window : globalThis);
