/* ShelfLife — dev/ingest-foods.js
   Ingest agent-authored food batches (dev/foods-batch-*.json — arrays of
   food entries) into js/data/foods-extra.js after strict validation:
   required fields, category/unit enums, gpu for count foods, USDA-shaped
   nutrition, feasible shelf triple, spoilage prose, id uniqueness. Subs
   referencing unknown ids are dropped (cross-batch refs resolve on the
   second pass). Usage: node dev/ingest-foods.js */
'use strict';
const fs = require('fs');
const path = require('path');
const mem = {};
globalThis.localStorage = {
  getItem: (k) => mem[k] ?? null, setItem: (k, v) => { mem[k] = String(v); },
  removeItem: (k) => { delete mem[k]; }, key: (i) => Object.keys(mem)[i] || null,
  get length() { return Object.keys(mem).length; }
};
['js/util.js', 'js/data/foods.js'].forEach((f) => eval(fs.readFileSync(path.join(__dirname, '..', f), 'utf8')));
const CORE = globalThis.SL.foods;

const CATS = ['produce', 'protein', 'dairy', 'bakery', 'frozen', 'canned', 'pantry', 'spice'];
const UNITS = ['g', 'ml', 'ct'];
const STORAGES = ['pantry', 'fridge', 'freezer'];

const coreIds = new Set(CORE.list.map((f) => f.id));
const taken = new Set(coreIds);
const kept = [], errors = [];

function bad(id, why) { errors.push(id + ': ' + why); }

const batchFiles = fs.readdirSync(__dirname).filter((f) => /^foods-batch-.+\.json$/.test(f)).sort();
if (!batchFiles.length) { console.error('no dev/foods-batch-*.json files found'); process.exit(1); }

batchFiles.forEach((file) => {
  const entries = JSON.parse(fs.readFileSync(path.join(__dirname, file), 'utf8'));
  entries.forEach((f) => {
    if (!f || typeof f !== 'object') return;
    const id = String(f.id || '').toLowerCase().replace(/[^a-z0-9_]/g, '_');
    if (!id) return bad('(missing id)', 'no id in ' + file);
    if (taken.has(id)) return; // dupes across batches: first wins, silently
    if (!f.name || typeof f.name !== 'string') return bad(id, 'missing name');
    if (!Array.isArray(f.aliases) || !f.aliases.length) return bad(id, 'missing aliases');
    if (!CATS.includes(f.cat)) return bad(id, 'bad cat ' + f.cat);
    if (!UNITS.includes(f.unit)) return bad(id, 'bad unit ' + f.unit);
    if (f.unit === 'ct' && !(f.gpu > 0)) return bad(id, 'ct food missing gpu');
    if (!f.pkg || !(f.pkg.qty > 0) || !f.pkg.label) return bad(id, 'bad pkg');
    if (!(f.price > 0 && f.price < 100)) return bad(id, 'bad price ' + f.price);
    const n = f.nutr || {};
    if (!['cal', 'p', 'c', 'f', 'fib', 'na'].every((k) => typeof n[k] === 'number' && n[k] >= 0)) return bad(id, 'bad nutr');
    if (n.cal > 950) return bad(id, 'calories/100g implausible: ' + n.cal);
    const s = f.shelf || {};
    if (!['pantry', 'fridge', 'freezer'].every((k) => typeof s[k] === 'number' && s[k] >= 0)) return bad(id, 'bad shelf triple');
    if (!STORAGES.includes(f.storage)) return bad(id, 'bad storage');
    if (!(s[f.storage] > 0)) return bad(id, 'zero shelf life at default storage');
    if (!f.spoil || f.spoil.length < 40) return bad(id, 'spoilage prose too thin');
    f.id = id;
    f.subs = Array.isArray(f.subs) ? f.subs : [];
    taken.add(id);
    kept.push(f);
  });
});

// resolve subs now that every batch is merged; drop unknown references
const allIds = new Set([...taken]);
kept.forEach((f) => { f.subs = f.subs.filter((s) => allIds.has(s) && s !== f.id); });

const out = '/* ShelfLife — data/foods-extra.js\n' +
  '   Generated catalog extensions (' + kept.length + ' foods). REGENERATED by\n' +
  '   dev/ingest-foods.js — hand-edit foods.js for the curated core, not this file. */\n' +
  '(function (g) {\n  \'use strict\';\n  const EXTRA = ' +
  JSON.stringify(kept, null, 1).replace(/\n/g, '\n  ') +
  ';\n  if (g.SL && g.SL.foods && g.SL.foods.register) g.SL.foods.register(EXTRA);\n' +
  '})(typeof window !== \'undefined\' ? window : globalThis);\n';
fs.writeFileSync(path.join(__dirname, '..', 'js', 'data', 'foods-extra.js'), out);

console.log('ingested ' + kept.length + ' foods from ' + batchFiles.length + ' batches into js/data/foods-extra.js');
console.log('catalog total: ' + (coreIds.size + kept.length));
if (errors.length) { console.log('rejected ' + errors.length + ':'); errors.slice(0, 30).forEach((e) => console.log('  ' + e)); }
